<h1>Oprávnění</h1>
<div style="width: 50%">

    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
        <tr>
            <th>ID</th>
            <th>Uživatelské jméno</th>
            <th>Email</th>
            <th>Oprávnění</th>
        </tr>
        </thead>
        <tbody>

        <?php foreach ($users as $user) { ?>
            <tr>
                <td><a href="opravneni/<?= $user['user_id'] ?>/detail"><?= $user['user_id'] ?></a></td>
                <td><?= $user['user_name'] ?></td>
                <td><?= $user['user_email'] ?></td>
                <td><?= Permissions::tryFrom($user['user_permissions'])->name ?></td>
            </tr>

        <?php } ?>
        </tbody>
    </table>
</div>
<ul>


</ul>
<script>
    $(document).ready(function () {
        $('#example').DataTable({
            searching: false,
            pageLength: 5,
            lengthMenu: [5, 10, 15, 20, 25]
        });
    });
</script>