<h2>Registrace uživatele</h2>

<div style="width: 500px">
    <form id="registrace" class="registrace" method="post">
        <div class="form-group">
            <label for="name">Uživatelské jméno</label>
            <input type="text" class="form-control" name="name" id="name" placeholder="Uživatelské jméno" required>
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="email" class="form-control" name="email" id="email" placeholder="Email" required>
        </div>
        <div class="form-group">
            <label for="password">Heslo</label>
            <input type="password" class="form-control" name="password" id="password" placeholder="Heslo" required>
        </div>
        <div class="form-group">
            <label for="password2">Heslo znova</label>
            <input type="password" class="form-control" id="password2" placeholder="Heslo" required>
        </div>
        <button type="submit" class="btn btn-primary">Přihlásit se</button>
    </form>
</div>
<script>
    $('#registrace').submit(function (e){
        console.log('...')
        e.preventDefault();
        if ($('#password').val() !== $('#password2').val()){
            let div = $('<div class="toast" role="alert" aria-live="assertive" aria-atomic="true"> \
                <div class="toast-header"> \
                    <img src="https://static.vecteezy.com/system/resources/previews/012/042/292/original/warning-sign-icon-transparent-background-free-png.png" class="rounded mr-2" alt="..." style="max-height: 25px; max-width: 25px"> \
                    <strong class="mr-auto">Chyba</strong> \
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close"> \
                    <span aria-hidden="true">&times;</span> \
                </button> \
                </div> \
                <div class="toast-body"> \
                    Hesla se neshodují. \
                </div> \
                </div>'
            )

            $("#toasts").append(div)
            div.toast({autohide: true, delay: 3000})
            div.toast('show')
            div.on('hidden.bs.toast', function (){
                div.remove()
            })
        } else {
            e.currentTarget.submit();
        }

    })

</script>
